language: python
python:
  - "2.7"
sudo: false
cache: pip
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - gfortran
before_install:
  - travis_retry pip install -q numpy==1.8.0
  - travis_wait pip install -q scipy==0.13.2
  - pip install -q pytest
  - pip install -q coveralls
#install:
#  - python setup.py install
script:
  - coverage run --source=cosine_transform -m py.test -v tests
after_success:
  - coveralls